javaOpts: -Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512M
configServer: http://config-server:8080
listenPort: 80
containerPort: 8080
readinessPath: /manage/health
readinessDelay: 60
readinessTimeout: 5
readinessPeriod: 10
readinessSuccess: 1
readinessFailure: 6
livenessPath: /manage/health
livenessDelay: 120
livenessTimeout: 5
livenessPeriod: 10
livenessSuccess: 1
livenessFailure: 6
requestsCpu: 200m
requestsMemory: 512Mi
limitsCpu: 500m
limitsMemory: 800Mi
externalBalancer: no
isConfigServer: no
minReplicas: 1
maxReplicas: 3
targetCpu: 50
environment: local
