{{if .Values.configMapContent}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{required "A valid .Values.msName entry required!" .Values.msName | quote}}
  labels:
    app: {{required "A valid .Values.msName entry required!" .Values.msName | quote}}
data:
  application.yml: |
{{ .Values.configMapContent | indent 4}}
{{end}}
