---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{required "A valid .Values.msName entry required!" .Values.msName | quote}}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{required "A valid .Values.msName entry required!" .Values.msName | quote}}
  minReplicas: {{.Values.minReplicas}}
  maxReplicas: {{.Values.maxReplicas}}
  targetCPUUtilizationPercentage: {{.Values.targetCpu}}
